vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        vehicule_image:
            uri_prefix: /images/vehicules
            upload_destination: '%kernel.project_dir%/public/images/vehicules'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        client_image:
            uri_prefix: /images/clients
            upload_destination: '%kernel.project_dir%/public/images/clients'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
